# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Equ-ation

description: >- # this means to ignore newlines until "baseurl:"
  Entreprise de médiation animal equ-ation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://equ-ation.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "equ-ation.github.io"
github_username:  stalina

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

remote_theme: daattali/beautiful-jekyll

author: stalina

navbar-links:
#  Services: "/#services"
#  About Us: "/#aboutus"
#  Clients: "/#clients"
#  Open-Source: "/#portfolio"
  Me contacter: "/contact"

title-img: /assets/img/equation-white.png


site-css: "/assets/css/equation.css"

keywords: "equation, equ-ation, mediation, animale, animaux, mediation animale, mediation animale entreprise, mediation animale entreprise, mediation animale entreprise"

mobile-theme-col: "#0085A1"
navbar-col: "#004827"
navbar-text-col: "#fff"
navbar-border-col: "#004827"

social-network-links:
  email: "todo"
  github: stalina
  twitter: todo
  telephone: +32000000000

url-pretty: "equ-ation.github.io"

footer-img: "/assets/img/footer-bg.png"

gtag: "todo"

timezone: "France/Paris"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      footer-extra: custom_footer.html
      nav-short: true
      share-description: "Equ-ation entreprise de médiation animale, soins et services avec les animaux"
      share-img: "/assets/img/equation.png"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
